### ISSUE TITLE
Installing trainlib as library doesn't work

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#28]
## Install via git

I tried: `pip install "git+https://github.com/kbressem/trainlib.git#egg=trainlib"`

I get:
```
markus at MBP2021 in ~/Development/DeepSpA/tmp
(.venv)$ python
Python 3.9.7 (default, Oct 12 2021, 10:51:52)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from trainlib import transforms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/markus/Development/DeepSpA/tmp/.venv/lib/python3.9/site-packages/trainlib/transforms.py", line 6, in <module>
    from monai.utils.enums import CommonKeys
ImportError: cannot import name 'CommonKeys' from 'monai.utils.enums' (/Users/markus/Development/DeepSpA/tmp/.venv/lib/python3.9/site-packages/monai/utils/enums.py)
>>>
```
-> solved (was monai version issue)

## Install local

I tried: `pip install -e ../trainlib/`

I get:

```
markus at MBP2021 in ~/Development/DeepSpA/nako-spa (main●)
(.venv)$ ipython
zsh: /usr/local/bin/ipython: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
Python 3.7.12 (default, Oct 12 2021, 11:10:06)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

In [2]: import trainlib

In [3]: from trainlib import transforms
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-8eb3ef7ae6f5> in <module>
----> 1 from trainlib import transforms

~/Development/DeepSpA/trainlib/trainlib/transforms.py in <module>
      2 from typing import Callable, List
      3
----> 4 import monai
      5 from monai.transforms import Compose
      6 from monai.utils.enums import CommonKeys

~/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/__init__.py in <module>
     41
     42 # load directory modules only, skip loading individual files
---> 43 load_submodules(sys.modules[__name__], False, exclude_pattern=excludes)
     44
     45 # load all modules, this will trigger all export decorations

~/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/utils/module.py in load_submodules(basemod, load_all, exclude_pattern)
     73         if (is_pkg or load_all) and name not in sys.modules and match(exclude_pattern, name) is None:
     74             try:
---> 75                 mod = import_module(name)
     76                 importer.find_module(name).load_module(name)  # type: ignore
     77                 submodules.append(mod)

~/.pyenv/versions/3.7.12/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128
    129

~/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/apps/auto3dseg/__init__.py in <module>
     10 # limitations under the License.
     11
---> 12 from .auto_runner import AutoRunner
     13 from .bundle_gen import BundleAlgo, BundleGen
     14 from .data_analyzer import DataAnalyzer

~/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/apps/auto3dseg/auto_runner.py in <module>
     19 import torch
     20
---> 21 from monai.apps.auto3dseg.bundle_gen import BundleGen
     22 from monai.apps.auto3dseg.data_analyzer import DataAnalyzer
     23 from monai.apps.auto3dseg.ensemble_builder import (

~/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/apps/auto3dseg/bundle_gen.py in <module>
     22
     23 from monai.apps import download_and_extract
---> 24 from monai.apps.utils import get_logger
     25 from monai.auto3dseg.algo_gen import Algo, AlgoGen
     26 from monai.auto3dseg.utils import algo_to_pickle

ImportError: cannot import name 'get_logger' from 'monai.apps.utils' (/Users/markus/Development/DeepSpA/nako-spa/.venv/lib/python3.7/site-packages/monai/apps/utils.py)
```

Related: https://github.com/kbressem/nako-spa/pull/12

**Comment by kbressem** [comment]
I also believe, the error in nako-spa comes from monai.label and has nothing to do with `trainlib`. `from monai.apps.utils import get_logger` is not code from `trainlib`.

**Comment by markus-hinsche** [comment]
In `Install via git`, I didn't have any other deps installed, so `monai-weekly-0.5.dev2111` go installed via `pip install "git+https://github.com/kbressem/trainlib.git#egg=trainlib"`

**Comment by markus-hinsche** [comment]
In `Install local`,

```
markus at MBP2021 in ~/Development/DeepSpA/nako-spa (trainlib-as-lib)
(.venv)$ pip list | grep monai
monai                   1.0.0
monai-weekly            0.5.dev2111
```

**Comment by kbressem** [comment]
I wonder why `monai-weekly` is only 0.5 and not the newest release. But pinning the version in the `setup.cfg`, as done in #31 was a good idea. 

Does it work if you delete both and then reinstall? 

see here why deleting is necessary: 
https://docs.monai.io/en/stable/installation.html#weekly-preview-release

**Comment by kbressem** [comment]
@markus-hinsche is this still an issue?

**Comment by markus-hinsche** [comment]
Yes, this is an issue here:
https://github.com/kbressem/nako-spa/pull/12#discussion_r998628952

**Comment by markus-hinsche** [comment]
Here the issue appears again in transforms: 
https://gist.github.com/markus-hinsche/7596e278d7ba9ae5933914385a997859
